spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heeyoung?serverTimezone=Asia/Seoul
    username: root
    password: dpwl0910
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false